apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KC_DB_URL: "jdbc:mysql://host.docker.internal:3306/j_keycloak?allowPublicKeyRetrieval=true&useSSL=false"
  KC_DB_USERNAME: "root"
  KC_DB_PASSWORD: "root"