apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: jhcm
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: ghcr.io/vnworkday/jhcm-account:311d43e
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: account-configmap
            - secretRef:
                name: account-secret
          readinessProbe:
            httpGet:
              path: /account/actuator/health
              port: 8080
            initialDelaySeconds: 20 # you might want to adjust this value based on your application's startup time
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /account/actuator/health
              port: 8080
            initialDelaySeconds: 20 # you might want to adjust this value based on your application's startup time
            periodSeconds: 5
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "1"