apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: jhcm
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: ghcr.io/vnworkday/jhcm-account:na
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: account-configmap
            - secretRef:
                name: account-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10 # you might want to adjust this value based on your application's startup time
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10 # you might want to adjust this value based on your application's startup time
            periodSeconds: 5
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.2"