apiVersion: v1
kind: ConfigMap
metadata:
  name: {{service}}-configmap
  namespace: jhcm
data:
  HTTP_READ_TIMEOUT: "10000"
  HTTP_WRITE_TIMEOUT: "10000"
  HTTP_REQUEST_LOG_ENABLED: "true"
  HTTP_REQUEST_LOG_INCLUDE_HEADERS: "false"
  HTTP_RESPONSE_LOG_ENABLED: "true"
  HTTP_RESPONSE_LOG_INCLUDE_HEADERS: "false"