apiVersion: v1
kind: Service
metadata:
  name: {{service}}
  namespace: jhcm
  labels:
    app: {{service}}
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: {{service}}
  type: ClusterIP