apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: jhcm
spec:
  ingressClassName: nginx
  rules:
    - host: api.jhcm.io
      http:
        paths:
        - path: /account
          pathType: Prefix
          backend:
            service:
              name: account
              port:
                name: http
